- name: create database wordpress
  community.mysql.mysql_db:
    name: "{{ bd_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: create user mysql wordpress
  community.mysql.mysql_user:
    name: "{{ bd_user }}"
    host: "{{ item }}"
    password: "{{ bd_pass }}"
    priv: "{{ bd_name }}.*:ALL,GRANT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - localhost

- name: mariadb listen in all interfaces
  lineinfile:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "^bind-address            = 127.0.0.1"
    line: "bind-address            = 0.0.0.0"
    state: present
  notify:
    - restart mariadb

